### ISSUE TITLE
Update to address warning about using java11

### ISSUE THREAD

**Issue by basilv** [bcgov-nr/action-test-and-analyse#21]
Using bcgov-nr/action-test-and-analyse@v0.0.1 is giving a warning from SonarCloud bot:
The version of Java (11.0.17) you have used to run this analysis is deprecated and we will stop accepting it soon. Please update to at least Java 17. Read more [here](https://docs.sonarcloud.io/appendices/scanner-environment/)

See e.g. https://github.com/bcgov/nr-forests-access-management/pull/777#issuecomment-1675033663

We are NOT getting this warning when using the Sonar github action directly - e.g. SonarSource/sonarcloud-github-action@master

**Comment by DerekRoberts** [comment]
There was so little action in this repo that Dependabot went dormant!  Hopefully this is the fix: https://github.com/bcgov-nr/action-test-and-analyse/pull/23.

It's going out in the next release, which should be very soon.

**Comment by DerekRoberts** [comment]
Replaced by https://github.com/bcgov/nr-forests-access-management/issues/782
